# Generated by Django 5.0.6 on 2024-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dancer_dancestyle_dancerstyle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancer',
            options={'verbose_name': 'Танцор', 'verbose_name_plural': 'Танцоры'},
        ),
        migrations.AlterModelOptions(
            name='dancerstyle',
            options={'verbose_name': 'Выступление', 'verbose_name_plural': 'Выступления'},
        ),
        migrations.AlterModelOptions(
            name='dancestyle',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Обращение'),
        ),
    ]
