# Generated by Django 5.0.6 on 2024-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dancer_options_alter_dancerstyle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancerstyle',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
