# Generated by Django 5.0.6 on 2024-05-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dancerstyle_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancerstyle',
            name='event_date',
        ),
    ]
