# Generated by Django 5.0.6 on 2024-05-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_dancerstyle_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancerstyle',
            options={'verbose_name': 'Выступление', 'verbose_name_plural': 'Выступление'},
        ),
    ]
